[ADD] - unit test for Hospital::run added

diff --git a/EPITECH/D06/ex06/test/Makefile b/EPITECH/D06/ex06/test/Makefile
--- a/EPITECH/D06/ex06/test/Makefile
+++ b/EPITECH/D06/ex06/test/Makefile
@@ -5,7 +5,7 @@
 ## Login   <Adil Denia>
 ##
 ## Started on  Wed Jul 31 4:51:42 PM 2024 Paradis
-## Last update Sat Aug 9 6:19:20 PM 2024 Paradis
+## Last update Wed Aug 13 4:33:28 PM 2024 Paradis
 ##
 
 
@@ -37,24 +37,25 @@ OBJS_GCNO    	= 	$(SRCS:.cpp=.gcno)
 COVERAGE	 	= 	../../../../coverage.*
 LOG 			= 	*.log 
 VGCORE			=	vgcore.*
+REPORT			=	*.report
 all				: 	$(NAME)
 
 $(NAME)			: 	$(OBJS)
 					$(G++) $(CPPFLAGS) $(OBJS) -o $(NAME)
-					# @echo "Current working directory: $$PWD"
-					# @valgrind --leak-check=full --trace-children=yes --show-leak-kinds=all --error-exitcode=1 ./$(NAME) 2>&1 | tee valgrind_output.log || true
-					# @if ! grep -q "definitely lost" valgrind_output.log; \
-					# then \
-					# 	echo -e "\033[32mNo memory leaks detected, running unit tests...\033[0m"; \
-					# else \
-					# 	echo -e "\033[31mMemory leaks detected, aborting.\033[0m"; \
-					# 	exit 1; \
-					# fi
+					@echo "Current working directory: $$PWD"
+					@valgrind --leak-check=full --trace-children=yes --show-leak-kinds=all --error-exitcode=1 ./$(NAME) 2>&1 | tee valgrind_output.log || true
+					@if ! grep -q "definitely lost" valgrind_output.log; \
+					then \
+						echo -e "\033[32mNo memory leaks detected, running unit tests...\033[0m"; \
+					else \
+						echo -e "\033[31mMemory leaks detected, aborting.\033[0m"; \
+						exit 1; \
+					fi
 
 RM 				= 	rm -rf
 
 clean			:
-					$(RM) $(OBJS) $(OBJS_GCDA) $(OBJS_GCNO) $(COVERAGE) $(LOG) $(VGCORE)
+					$(RM) $(OBJS) $(OBJS_GCDA) $(OBJS_GCNO) $(COVERAGE) $(LOG) $(VGCORE) $(REPORT)
 
 fclean			: 	clean
 					$(RM) $(NAME)
