[UPDATE] - readme and it is completed. [UPDATE] - Makefiles

diff --git a/CPP_00/EPITECH/D06/ex03/Makefile b/CPP_00/EPITECH/D06/ex03/Makefile
--- a/CPP_00/EPITECH/D06/ex03/Makefile
+++ b/CPP_00/EPITECH/D06/ex03/Makefile
@@ -5,7 +5,7 @@
 ## Login   <Adil Denia>
 ##
 ## Started on  Thu Jul 25 7:30:59 PM 2024 Paradis
-## Last update Tue Jul 29 6:32:33 PM 2024 Paradis
+## Last update Tue Aug 26 5:03:43 PM 2024 Paradis
 ##
 
 # # Compilateur
@@ -46,7 +46,17 @@ all			:	$(NAME)
 
 $(NAME)		:	$(OBJS)
 				$(G++) $(CPPFLAGS) $(OBJS) -o $(NAME) 
-				
+
+VALGRIND	:	$(NAME)
+				@echo "Current working directory: $$PWD"
+				@valgrind --leak-check=full --trace-children=yes --show-leak-kinds=all --error-exitcode=1 ./$(NAME) 2>&1 | tee valgrind_output.log || true
+				@if ! grep -q "definitely lost" valgrind_output.log; \
+				then \
+					echo -e "\033[32mNo memory leaks detected, running unit tests...\033[0m"; \
+				else \
+					echo -e "\033[31mMemory leaks detected, aborting.\033[0m"; \
+					exit 1; \
+				fi
 # # Rule for clean files object
 clean		:
 				$(RM) $(OBJS) $(LOG)
diff --git a/CPP_00/EPITECH/D06/ex05/test/Makefile b/CPP_00/EPITECH/D06/ex05/test/Makefile
--- a/CPP_00/EPITECH/D06/ex05/test/Makefile
+++ b/CPP_00/EPITECH/D06/ex05/test/Makefile
@@ -5,7 +5,7 @@
 ## Login   <Adil Denia>
 ##
 ## Started on  Wed Jul 31 4:51:42 PM 2024 Paradis
-## Last update Fri Aug 8 9:24:33 PM 2024 Paradis
+## Last update Tue Aug 26 5:17:17 PM 2024 Paradis
 ##
 
 
@@ -40,15 +40,17 @@ all				: 	$(NAME)
 
 $(NAME)			: 	$(OBJS)
 					$(G++) $(CPPFLAGS) $(OBJS) -o $(NAME)
-					# @echo "Current working directory: $$PWD"
-					# @valgrind --leak-check=full --trace-children=yes --show-leak-kinds=all --error-exitcode=1 ./$(NAME) 2>&1 | tee valgrind_output.log || true
-					# @if ! grep -q "definitely lost" valgrind_output.log; \
-					# then \
-					# 	echo -e "\033[32mNo memory leaks detected, running unit tests...\033[0m"; \
-					# else \
-					# 	echo -e "\033[31mMemory leaks detected, aborting.\033[0m"; \
-					# 	exit 1; \
-					# fi
+
+VALGRIND		:	$(NAME)
+					@echo "Current working directory: $$PWD"
+					@valgrind --leak-check=full --trace-children=yes --show-leak-kinds=all --error-exitcode=1 ./$(NAME) 2>&1 | tee valgrind_output.log || true
+					@if ! grep -q "definitely lost" valgrind_output.log; \
+					then \
+						echo -e "\033[32mNo memory leaks detected, running unit tests...\033[0m"; \
+					else \
+						echo -e "\033[31mMemory leaks detected, aborting.\033[0m"; \
+						exit 1; \
+					fi
 
 RM 				= 	rm -rf
 
