[UPDATE] - readme and it is completed. [UPDATE] - Makefiles

diff --git a/CPP_00/EPITECH/D06/ex02/Makefile b/CPP_00/EPITECH/D06/ex02/Makefile
--- a/CPP_00/EPITECH/D06/ex02/Makefile
+++ b/CPP_00/EPITECH/D06/ex02/Makefile
@@ -5,7 +5,7 @@
 ## Login   <Adil Denia>
 ##
 ## Started on  Thu Jul 25 7:30:59 PM 2024 Paradis
-## Last update Sat Jul 26 8:57:19 PM 2024 Paradis
+## Last update Tue Aug 26 4:58:14 PM 2024 Paradis
 ##
 
 # # Compilateur
@@ -45,7 +45,18 @@ all			:	$(NAME)
 
 $(NAME)		:	$(OBJS)
 				$(G++) $(CPPFLAGS) $(OBJS) -o $(NAME) 
-				
+
+VALGRIND	:	$(OBJS)
+				$(G++) $(CPPFLAGS) $(OBJS) -o $(NAME) 
+				@echo "Current working directory: $$PWD"
+				@valgrind --leak-check=full --trace-children=yes --show-leak-kinds=all --error-exitcode=1 ./$(NAME) 2>&1 | tee valgrind_output.log || true
+				@if ! grep -q "definitely lost" valgrind_output.log; \
+				then \
+					echo -e "\033[32mNo memory leaks detected, running unit tests...\033[0m"; \
+				else \
+					echo -e "\033[31mMemory leaks detected, aborting.\033[0m"; \
+					exit 1; \
+				fi
 # # Rule for clean files object
 clean		:
 				$(RM) $(OBJS) $(LOG)
