[ADD] - feat: unit test for multiple arguments added. [UPDATE] - feat: Makefiles updated for check memory leaks

diff --git a/42/M00/ex00/test/Makefile b/42/M00/ex00/test/Makefile
--- a/42/M00/ex00/test/Makefile
+++ b/42/M00/ex00/test/Makefile
@@ -1,7 +1,7 @@
 G++           	= g++
 #############################################
-SRC_PATH		= ../ex00/source
-INC_PATH 		= ../ex00/include
+SRC_PATH		= ../source
+INC_PATH 		= ../include
 BIN_PATH 		= ./bin
 
 NAME          	= test_Megaphone
@@ -9,25 +9,33 @@ NAME          	= test_Megaphone
 
 INCFLAGS     	+= -I $(INC_PATH)
 CRITFLAGS    	+=  --coverage -lcriterion
-CPPFLAGS     	+= -g -Wall -Wextra -Werror -W -Wfatal-errors std=c++23 $(INCFLAGS) $(CRITFLAGS)
+CPPFLAGS     	+= -g -Wall -Wextra -Werror -W -Wfatal-errors -std=c++11 $(INCFLAGS) $(CRITFLAGS)
 
 SRCS         = $(BIN_PATH)/test_main.cpp \
-               $(SRC_PATH)/test.cpp
+               $(SRC_PATH)/Megaphone.cpp
 
 OBJS         = $(SRCS:.cpp=.o)
 OBJS_GCDA    = $(SRCS:.cpp=.gcda)
 OBJS_GCNO    = $(SRCS:.cpp=.gcno)
-COVERAGE	 = ../../coverage.* 
+COVERAGE	 = ../../../../coverage.*
+LOG 		= *.log 
 
 all: $(NAME)
 
-$(NAME): $(OBJS)
-	$(G++) $(CPPFLAGS) $(OBJS) -o $(NAME)
-
+$(NAME): 	$(OBJS)
+			$(G++) $(CPPFLAGS) $(OBJS) -o $(NAME)
+			@valgrind --leak-check=full --show-leak-kinds=all  --error-exitcode=1 ./$(NAME) 2>&1 | tee valgrind_output.log || true
+			@if ! grep -q "definitely lost" valgrind_output.log; \
+			then \
+				echo -e "\033[32mNo memory leaks detected, running unit tests...\033[0m"; \
+			else \
+				echo -e "\033[31mMemory leaks detected, aborting.\033[0m"; \
+				exit 1; \
+			fi
 RM = rm -rf
 
 clean:
-	$(RM) $(OBJS) $(OBJS_GCDA) $(OBJS_GCNO) $(COVERAGE)
+	$(RM) $(OBJS) $(OBJS_GCDA) $(OBJS_GCNO) $(COVERAGE) $(LOG)
 
 fclean: clean
 	$(RM) $(NAME)
